 # Only use spaces to indent your .yml configuration.
 # -----
 # You can specify a custom docker image from Docker Hub as your build environment.
 image: microsoft/dotnet:sdk
 
 pipelines:
   default:
       - step:
           max-time: 2
           script: # Modify the commands below to build your repository.
             - docker version
             - docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Password123!" -p 1433:1433 -d "mcr.microsoft.com/mssql/server"
             - dotnet test SP19.P05.Tests
           services:
             - docker
 
 definitions:
   services:
     docker:
       memory: 2048